# Generated by Django 5.2.7 on 2026-03-09 16:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0004_alter_formation_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Format de téléphone invalide')])),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(choices=[('tunisie', 'Tunisie'), ('france', 'France'), ('algerie', 'Algérie'), ('maroc', 'Maroc'), ('belgique', 'Belgique'), ('canada', 'Canada'), ('autre', 'Autre')], default='tunisie', max_length=50)),
                ('source', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('google', 'Google'), ('site_web', 'Site web'), ('recommandation', 'Recommandation'), ('appel_entrant', 'Appel entrant'), ('autre', 'Autre')], default='site_web', max_length=50)),
                ('type_prospect', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20)),
                ('service_recherche', models.CharField(choices=[('formation', 'Formation'), ('consulting', 'Consulting'), ('les_deux', 'Les deux')], default='formation', max_length=20)),
                ('niveau_estime', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('mode_prefere', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('hybride', 'Hybride')], default='presentiel', max_length=20)),
                ('disponibilite', models.CharField(blank=True, help_text='Dates, horaires de disponibilité', max_length=200)),
                ('canal_contact_prefere', models.CharField(choices=[('telephone', 'Téléphone'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20)),
                ('commentaires', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('en_cours', 'En cours'), ('qualifie', 'Qualifié'), ('converti', 'Converti'), ('perdu', 'Perdu')], default='nouveau', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('formations_souhaitees', models.ManyToManyField(blank=True, help_text='Formations souhaitées par le prospect', related_name='prospects', to='formation.formation')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_suivis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_echange', models.CharField(choices=[('appel', 'Appel téléphonique'), ('email', 'Email'), ('rdv', 'Rendez-vous'), ('message', 'Message WhatsApp'), ('autre', 'Autre')], max_length=20)),
                ('date_echange', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='prospects.prospect')),
            ],
            options={
                'verbose_name': "Historique d'échange",
                'verbose_name_plural': "Historiques d'échanges",
                'ordering': ['-date_echange'],
            },
        ),
    ]
