# Generated by Django 6.0.4 on 2026-04-16 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("telephone", models.CharField(max_length=20, unique=True)),
                ("ville", models.CharField(max_length=100)),
                (
                    "pays",
                    models.CharField(
                        choices=[
                            ("tunisie", "Tunisie"),
                            ("france", "France"),
                            ("algerie", "Algérie"),
                            ("maroc", "Maroc"),
                            ("belgique", "Belgique"),
                            ("canada", "Canada"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("homme", "Homme"),
                            ("femme", "Femme"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "niveau_etudes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primaire", "Primaire"),
                            ("preparatoire", "Préparatoire"),
                            ("secondaire", "Secondaire"),
                            ("universitaire", "Universitaire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "diplome_obtenu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bac", "Bac"),
                            ("licence", "Licence"),
                            ("master", "Master"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                            ("google", "Google"),
                            ("site_web", "Site web"),
                            ("recommandation", "Recommandation"),
                            ("appel_entrant", "Appel entrant"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "niveau_estime",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode_prefere",
                    models.CharField(
                        choices=[
                            ("presentiel", "Présentiel"),
                            ("en_ligne", "En ligne"),
                            ("hybride", "Hybride"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "canal_contact_prefere",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("telephone", "Téléphone"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("commentaires", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("contacte", "Contacté"),
                            ("interesse", "Intéressé"),
                            ("converti", "Converti"),
                            ("perdu", "Perdu"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "formations_souhaitees",
                    models.ManyToManyField(
                        blank=True, related_name="prospects", to="formation.formation"
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects_suivis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospect",
                "verbose_name_plural": "Prospects",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueEchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_echange",
                    models.CharField(
                        choices=[
                            ("appel", "Appel téléphonique"),
                            ("email", "Email"),
                            ("rdv", "Rendez-vous"),
                            ("message", "Message WhatsApp"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_echange", models.DateTimeField(auto_now_add=True)),
                ("contenu", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'échange",
                "verbose_name_plural": "Historiques d'échanges",
                "ordering": ["-date_echange"],
            },
        ),
        migrations.CreateModel(
            name="Relance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_relance", models.DateField()),
                ("commentaire", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("aujourd_hui", "Aujourd'hui"),
                            ("en_retard", "En retard"),
                            ("fait", "Fait"),
                        ],
                        default="a_venir",
                        max_length=20,
                    ),
                ),
                ("date_action", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relances_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relances",
                        to="formation.formation",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances",
                        to="prospects.prospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relance",
                "verbose_name_plural": "Relances",
                "ordering": ["date_relance"],
            },
        ),
    ]
