# Generated by Django 5.2.7 on 2026-03-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
    ]
