# Generated by Django 5.2.7 on 2026-03-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_alter_prospect_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='canal_contact_prefere',
            field=models.CharField(blank=True, choices=[('telephone', 'Téléphone'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mode_prefere',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('hybride', 'Hybride')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='niveau_estime',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pays',
            field=models.CharField(choices=[('tunisie', 'Tunisie'), ('france', 'France'), ('algerie', 'Algérie'), ('maroc', 'Maroc'), ('belgique', 'Belgique'), ('canada', 'Canada'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='service_recherche',
            field=models.CharField(choices=[('formation', 'Formation'), ('consulting', 'Consulting'), ('les_deux', 'Les deux')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('google', 'Google'), ('site_web', 'Site web'), ('recommandation', 'Recommandation'), ('appel_entrant', 'Appel entrant'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('en_cours', 'En cours'), ('qualifie', 'Qualifié'), ('converti', 'Converti'), ('perdu', 'Perdu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='type_prospect',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
