# Generated by Django 5.2.7 on 2026-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_alter_prospect_canal_contact_prefere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
