# Generated by Django 5.2.7 on 2026-03-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_alter_prospect_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('interesse', 'Intéressé'), ('converti', 'Converti'), ('perdu', 'Perdu')], max_length=20),
        ),
    ]
