# Generated by Django 5.2.7 on 2026-03-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_alter_formation_description'),
        ('prospects', '0005_alter_prospect_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='diplome_obtenu',
            field=models.CharField(blank=True, choices=[('baccalaureat', 'Baccalauréat'), ('licence', 'Licence'), ('master', 'Master'), ('aucun', 'Aucun'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AddField(
            model_name='prospect',
            name='genre',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=10),
        ),
        migrations.AddField(
            model_name='prospect',
            name='niveau_etudes',
            field=models.CharField(blank=True, choices=[('lycee', 'Lycée'), ('bac', 'Bac'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='disponibilite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='formations_souhaitees',
            field=models.ManyToManyField(blank=True, related_name='prospects', to='formation.formation'),
        ),
    ]
