# Generated by Django 5.2.7 on 2026-03-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0006_prospect_date_naissance_prospect_diplome_obtenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='disponibilite',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='service_recherche',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='type_prospect',
        ),
    ]
