# Generated by Django 5.2.7 on 2026-03-27 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0008_alter_prospect_diplome_obtenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
