# Generated by Django 5.2.7 on 2026-03-28 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0009_alter_prospect_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relance', models.DateField()),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('aujourd_hui', "Aujourd'hui"), ('en_retard', 'En retard'), ('fait', 'Fait')], default='a_venir', max_length=20)),
                ('date_action', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_creees', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='prospects.prospect')),
            ],
            options={
                'verbose_name': 'Relance',
                'verbose_name_plural': 'Relances',
                'ordering': ['date_relance'],
            },
        ),
    ]
