# Generated by Django 5.2.7 on 2026-04-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_alter_formation_niveau'),
        ('prospects', '0010_relance'),
    ]

    operations = [
        migrations.AddField(
            model_name='relance',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances', to='formation.formation'),
        ),
    ]
