# Generated by Django 6.0.4 on 2026-04-16 12:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro doit être tunisien (ex: +21655123456 ou 55123456)",
                                regex="^(\\+216)?[2459]\\d{7}$",
                            )
                        ],
                    ),
                ),
                ("adresse", models.CharField(blank=True, default="", max_length=255)),
                (
                    "specialites",
                    models.TextField(help_text="Ex: Django, IA, Marketing Digital"),
                ),
                (
                    "niveau_intervention",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("universitaire", "Universitaire"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[("interne", "Interne"), ("vacation", "Vacation")],
                        max_length=20,
                    ),
                ),
                (
                    "cv_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/formateurs/cv/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("est_actif", models.BooleanField(default=True, editable=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiplomePDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="documents/formateurs/diplomes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "formateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diplomes",
                        to="formateurs.formateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContratPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="documents/formateurs/contrats/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "formateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="formateurs.formateur",
                    ),
                ),
            ],
        ),
    ]
