# Generated by Django 5.2.7 on 2026-03-04 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='telephone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro doit être tunisien (ex: +21655123456 ou 55123456)', regex='^(\\+216)?[2459]\\d{7}$')]),
        ),
    ]
