# Generated by Django 6.0.2 on 2026-03-12 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formateurs", "0002_alter_formateur_telephone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formateur",
            name="contrat_pdf",
        ),
        migrations.RemoveField(
            model_name="formateur",
            name="diplomes_pdf",
        ),
        migrations.RemoveField(
            model_name="formateur",
            name="disponibilites",
        ),
        migrations.RemoveField(
            model_name="formateur",
            name="heures_realisees",
        ),
        migrations.AlterField(
            model_name="formateur",
            name="adresse",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="formateur",
            name="telephone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro doit être tunisien (ex: +21655123456 ou 55123456)",
                        regex="^(\\+216)?[2459]\\d{7}$",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="ContratPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="documents/formateurs/contrats/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "formateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="formateurs.formateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiplomePDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="documents/formateurs/diplomes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "formateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diplomes",
                        to="formateurs.formateur",
                    ),
                ),
            ],
        ),
    ]
