# Generated by Django 6.0.2 on 2026-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formateurs", "0003_remove_formateur_contrat_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formateur",
            name="est_actif",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
