# Generated by Django 6.0.2 on 2026-03-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formateurs", "0005_alter_formateur_est_actif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formateur",
            name="est_actif",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
