# Generated by Django 6.0.2 on 2026-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('responsable', 'Responsable Pédagogique'), ('assistante', 'Assistante'), ('entreprise', 'Entreprise Partenaire'), ('formateur', 'Formateur'), ('etudiant', 'Étudiant')], default='etudiant', max_length=20),
        ),
    ]
