# Generated by Django 6.0.2 on 2026-02-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('responsable', 'Responsable Pédagogique')], default='responsable', max_length=20),
        ),
    ]
