# Generated by Django 5.2.7 on 2026-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe (affiché)'),
        ),
    ]
