<<<<<<< HEAD
# Generated by Django 5.2.7 on 2026-03-02 10:35
=======
# Generated by Django 6.0.2 on 2026-03-02 10:30
>>>>>>> a5808e50af6f05c8144c30ed907aebb831239cc4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_password_plain'),

    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('responsable', 'Responsable Pédagogique')], default='etudiant', max_length=20),
=======
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrateur"),
                    ("responsable", "Responsable Pédagogique"),
                ],
                default="etudiant",
                max_length=20,
            ),
>>>>>>> a5808e50af6f05c8144c30ed907aebb831239cc4
        ),
    ]
