# Generated by Django 6.0.2 on 2026-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_password_plain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Administrateur"),
                    ("responsable", "Responsable Pédagogique"),
                ],
                default="etudiant",
                max_length=20,
            ),
        ),
    ]
