# Generated by Django 6.0.4 on 2026-04-16 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diplomes", "0001_initial"),
        ("etudiants", "0001_initial"),
        ("formation", "0001_initial"),
        ("prospects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objet",
                    models.CharField(max_length=255, verbose_name="Ligne d'objet"),
                ),
                (
                    "apercu",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Texte d'aperçu"
                    ),
                ),
                ("message", models.TextField(verbose_name="Corps du message")),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="marketing_mail/pieces_jointes/%Y/%m/",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "send_mode",
                    models.CharField(
                        choices=[
                            ("direct", "Adresse e-mail directe"),
                            ("segment", "Segment de contacts"),
                        ],
                        default="segment",
                        max_length=10,
                        verbose_name="Mode d'envoi",
                    ),
                ),
                (
                    "email_direct",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Adresse e-mail directe",
                    ),
                ),
                (
                    "groupe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Prospects", "Prospects"),
                            ("Étudiants", "Étudiants"),
                            ("Diplômés", "Diplômés"),
                        ],
                        max_length=20,
                        verbose_name="Groupe cible",
                    ),
                ),
                (
                    "statuts_prospects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ex: ['nouveau', 'contacte', 'interesse']",
                        verbose_name="Statuts prospects ciblés",
                    ),
                ),
                (
                    "sources_prospects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ex: ['facebook', 'instagram', 'linkedin']",
                        verbose_name="Sources prospects ciblées",
                    ),
                ),
                (
                    "nombre_destinataires",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Calculé au moment de l'envoi",
                        verbose_name="Nombre de destinataires",
                    ),
                ),
                (
                    "est_archive",
                    models.BooleanField(default=False, verbose_name="Archivé"),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "envoye_par",
                    models.ForeignKey(
                        help_text="Utilisateur connecté qui a envoyé l'email",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_marketing",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Envoyé par",
                    ),
                ),
                (
                    "formations_cibles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="emails_marketing",
                        to="formation.formation",
                        verbose_name="Formations ciblées",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Marketing",
                "verbose_name_plural": "Emails Marketing",
                "db_table": "marketing_emails",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="DestinatairEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_adresse",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "type_destinataire",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("etudiant", "Étudiant"),
                            ("diplome", "Diplômé"),
                            ("direct", "Email direct"),
                        ],
                        max_length=10,
                        verbose_name="Type de destinataire",
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "diplome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_recus",
                        to="diplomes.diplome",
                        verbose_name="Diplômé",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_recus",
                        to="etudiants.etudiant",
                        verbose_name="Étudiant",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_recus",
                        to="prospects.prospect",
                        verbose_name="Prospect",
                    ),
                ),
                (
                    "email_marketing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinataires",
                        to="marketing_mail.marketingemail",
                        verbose_name="Email marketing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinataire Email",
                "verbose_name_plural": "Destinataires Emails",
                "db_table": "marketing_email_destinataires",
                "ordering": ["-date_envoi"],
            },
        ),
    ]
