# Generated by Django 6.0.4 on 2026-04-16 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("formateurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("objectifs_pedagogiques", models.TextField()),
                ("prerequis", models.TextField(blank=True, null=True)),
                (
                    "niveau",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "duree",
                    models.PositiveIntegerField(help_text="Durée totale en heures"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("presentiel", "Présentiel"),
                            ("en_ligne", "En ligne"),
                            ("hybride", "Hybride"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("prix_ht", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_ttc", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "nb_tranches_paiement",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre de tranches pour le paiement (1 = paiement unique)",
                    ),
                ),
                ("est_active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to="categories.categorie",
                    ),
                ),
                (
                    "formateurs",
                    models.ManyToManyField(
                        blank=True, related_name="formations", to="formateurs.formateur"
                    ),
                ),
            ],
        ),
    ]
