# Generated by Django 5.2.7 on 2026-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='nb_tranches_paiement',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de tranches pour le paiement (1 = paiement unique)'),
        ),
    ]
