# Generated by Django 5.2.7 on 2026-03-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0001_initial'),
        ('formation', '0002_formation_nb_tranches_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formateurs',
            field=models.ManyToManyField(blank=True, related_name='formations', to='formateurs.formateur'),
        ),
    ]
