# Generated by Django 5.2.7 on 2026-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_formation_formateurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
