# Generated by Django 6.0.2 on 2026-03-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formation", "0004_alter_formation_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formation",
            name="niveau",
            field=models.CharField(
                blank=True,
                choices=[
                    ("debutant", "Débutant"),
                    ("intermediaire", "Intermédiaire"),
                    ("avance", "Avancé"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
