# Generated by Django 6.0.2 on 2026-03-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_categorie_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="actif",
            field=models.BooleanField(default=True),
        ),
    ]
