# Generated by Django 6.0.4 on 2026-04-16 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=30)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("pays", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("formation_intitule", models.CharField(blank=True, max_length=255)),
                ("formation_duree", models.CharField(blank=True, max_length=50)),
                ("date_attestation", models.DateField()),
                ("seances_total", models.PositiveIntegerField(default=0)),
                ("absences", models.PositiveIntegerField(default=0)),
                ("etudiant_id_origine", models.IntegerField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diplomes",
                        to="formation.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diplômé",
                "verbose_name_plural": "Diplômés",
                "ordering": ["-date_attestation", "-date_creation"],
                "unique_together": {("etudiant_id_origine", "formation")},
            },
        ),
        migrations.CreateModel(
            name="DiplomeRelance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_relance", models.DateField()),
                ("commentaire", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("aujourd_hui", "Aujourd'hui"),
                            ("en_retard", "En retard"),
                            ("fait", "Fait"),
                        ],
                        default="a_venir",
                        max_length=20,
                    ),
                ),
                ("date_action", models.DateTimeField(blank=True, null=True)),
                ("notes_action", models.TextField(blank=True, default="")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relances_diplomes_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diplome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances",
                        to="diplomes.diplome",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relances_diplomes",
                        to="formation.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relance diplômé",
                "verbose_name_plural": "Relances diplômés",
                "ordering": ["date_relance"],
            },
        ),
    ]
