# Generated by Django 5.2.7 on 2026-04-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0005_alter_formation_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('formation_intitule', models.CharField(blank=True, max_length=255)),
                ('formation_duree', models.CharField(blank=True, max_length=50)),
                ('date_attestation', models.DateField(help_text="Date figurant sur l'attestation")),
                ('seances_total', models.PositiveIntegerField(default=0)),
                ('absences', models.PositiveIntegerField(default=0)),
                ('etudiant_id_origine', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='diplomes',
                    to='formation.formation'
                )),
            ],
            options={
                'verbose_name': 'Diplômé',
                'verbose_name_plural': 'Diplômés',
                'ordering': ['-date_attestation', '-date_creation'],
                'unique_together': {('etudiant_id_origine', 'formation')},
            },
        ),
    ]