# Generated by Django 6.0.2 on 2026-04-06 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("etudiants", "0006_alter_etudiant_email"),
        ("formation", "0005_alter_formation_niveau"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("attestation_reussite", "Attestation de Réussite"),
                            ("diplome", "Diplôme"),
                            ("certificat", "Certificat de Formation"),
                        ],
                        default="attestation_reussite",
                        max_length=30,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_delivrance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de délivrance"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "numero_diplome",
                    models.CharField(
                        blank=True,
                        help_text="Numéro unique généré automatiquement",
                        max_length=50,
                        unique=True,
                        verbose_name="Numéro de diplôme",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("pret", "Prêt à délivrer"),
                            ("delivre", "Délivré"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        blank=True,
                        help_text="L'étudiant concerné (optionnel pour l'historique)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diplomes",
                        to="etudiants.etudiant",
                        verbose_name="Étudiant lié",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        help_text="Formation suivie avec succès",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diplomes",
                        to="formation.formation",
                        verbose_name="Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diplôme / Attestation",
                "verbose_name_plural": "Diplômes / Attestations",
                "ordering": ["-date_creation"],
            },
        ),
    ]
