# Generated by Django 5.2.7 on 2026-04-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomes', '0001_initial'),
        ('formation', '0005_alter_formation_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='formation',
            field=models.ForeignKey(blank=True, help_text='FK vers la formation (peut devenir null si la formation est supprimée)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes', to='formation.formation'),
        ),
    ]
