# Generated by Django 5.2.7 on 2026-04-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomes', '0003_alter_diplome_date_attestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomerelance',
            name='notes_action',
            field=models.TextField(blank=True, default=''),
        ),
    ]
