# Generated by Django 5.2.7 on 2026-03-16 13:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formation', '0004_alter_formation_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(choices=[('tunisie', 'Tunisie'), ('france', 'France'), ('algerie', 'Algérie'), ('maroc', 'Maroc'), ('belgique', 'Belgique'), ('canada', 'Canada'), ('autre', 'Autre')], max_length=50)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=10)),
                ('niveau_etudes', models.CharField(blank=True, choices=[('lycee', 'Lycée'), ('bac', 'Bac'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=20)),
                ('diplome_obtenu', models.CharField(blank=True, choices=[('baccalaureat', 'Baccalauréat'), ('licence', 'Licence'), ('master', 'Master'), ('aucun', 'Aucun'), ('autre', 'Autre')], max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('abandonne', 'Abandonné'), ('certifie', 'Certifié')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formations_suivies', models.ManyToManyField(blank=True, help_text="Formations suivies par l'étudiant", related_name='etudiants', to='formation.formation')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants_suivis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cin', 'CIN'), ('cv', 'CV'), ('contrat', 'Contrat'), ('recu', 'Reçu'), ('rne', 'RNE'), ('autre', 'Autre')], max_length=20)),
                ('fichier', models.FileField(upload_to='etudiants/documents/%Y/%m/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='etudiants.etudiant')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('partiel', 'Partiel'), ('complet', 'Complet')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='N° chèque, référence virement, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='etudiants.etudiant')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
