# Generated by Django 6.0.4 on 2026-04-16 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("formation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("telephone", models.CharField(max_length=20, unique=True)),
                ("ville", models.CharField(max_length=100)),
                (
                    "pays",
                    models.CharField(
                        choices=[
                            ("tunisie", "Tunisie"),
                            ("france", "France"),
                            ("algerie", "Algérie"),
                            ("maroc", "Maroc"),
                            ("belgique", "Belgique"),
                            ("canada", "Canada"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("homme", "Homme"),
                            ("femme", "Femme"),
                            ("autre", "Autre"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "niveau_etudes",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primaire", "Primaire"),
                            ("preparatoire", "Préparatoire"),
                            ("secondaire", "Secondaire"),
                            ("universitaire", "Universitaire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "diplome_obtenu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bac", "Bac"),
                            ("licence", "Licence"),
                            ("master", "Master"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_inscription", models.DateField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("actif", "Actif"), ("abandonne", "Abandonné")],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("espece", "Espèce"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                        ],
                        default="espece",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etudiants_suivis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Étudiant",
                "verbose_name_plural": "Étudiants",
                "ordering": ["-date_inscription", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("cin", "CIN"),
                            ("cv", "CV"),
                            ("contrat", "Contrat"),
                            ("recu", "Reçu"),
                            ("rne", "RNE"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="etudiants/documents/%Y/%m/",
                        verbose_name="Fichier (optionnel)",
                    ),
                ),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="etudiants.etudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-date_upload"],
            },
        ),
        migrations.CreateModel(
            name="EtudiantFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_inscription_formation", models.DateField(auto_now_add=True)),
                ("attestation", models.BooleanField(default=False)),
                ("date_attestation", models.DateField(blank=True, null=True)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etudiant_formations",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etudiant_formations",
                        to="formation.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription formation",
                "verbose_name_plural": "Inscriptions formations",
                "ordering": ["date_inscription_formation"],
                "unique_together": {("etudiant", "formation")},
            },
        ),
        migrations.AddField(
            model_name="etudiant",
            name="formations_suivies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Formations suivies par l'étudiant",
                related_name="etudiants",
                through="etudiants.EtudiantFormation",
                to="formation.formation",
            ),
        ),
        migrations.CreateModel(
            name="EtudiantRelance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_relance", models.DateField()),
                ("commentaire", models.TextField(blank=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("aujourd_hui", "Aujourd'hui"),
                            ("en_retard", "En retard"),
                            ("fait", "Fait"),
                        ],
                        default="a_venir",
                        max_length=20,
                    ),
                ),
                ("date_action", models.DateTimeField(blank=True, null=True)),
                ("notes_action", models.TextField(blank=True, default="")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relances_etudiants_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances",
                        to="etudiants.etudiant",
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relances_etudiants",
                        to="formation.formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relance étudiant",
                "verbose_name_plural": "Relances étudiants",
                "ordering": ["date_relance"],
            },
        ),
    ]
