# Generated by Django 5.2.7 on 2026-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement')], default='espece', help_text='Mode de paiement par défaut', max_length=20),
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
