# Generated by Django 6.0.2 on 2026-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0002_etudiant_mode_paiement_delete_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="fichier",
            field=models.FileField(
                blank=True, null=True, upload_to="etudiants/documents/%Y/%m/"
            ),
        ),
    ]
