# Generated by Django 6.0.2 on 2026-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etudiants", "0003_alter_document_fichier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="commentaire",
            field=models.CharField(
                blank=True,
                help_text="Information supplémentaire sur le document (ex: document physique fourni)",
                max_length=255,
                verbose_name="Commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="date_upload",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date d'enregistrement"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="fichier",
            field=models.FileField(
                blank=True,
                help_text="Upload du fichier si disponible en version numérique",
                null=True,
                upload_to="etudiants/documents/%Y/%m/",
                verbose_name="Fichier (optionnel)",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("cin", "CIN"),
                    ("cv", "CV"),
                    ("contrat", "Contrat"),
                    ("recu", "Reçu"),
                    ("rne", "RNE"),
                    ("autre", "Autre"),
                ],
                max_length=20,
                verbose_name="Type de document",
            ),
        ),
    ]
