# Generated by Django 5.2.7 on 2026-03-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_alter_document_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='diplome_obtenu',
            field=models.CharField(blank=True, choices=[('bac', 'Bac'), ('licence', 'Licence'), ('master', 'Master'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau_etudes',
            field=models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('preparatoire', 'Préparatoire'), ('secondaire', 'Secondaire'), ('universitaire', 'Universitaire')], max_length=20),
        ),
    ]
