# Generated by Django 5.2.7 on 2026-04-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_alter_etudiant_email'),
        ('formation', '0005_alter_formation_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='etudiants/documents/%Y/%m/', verbose_name='Fichier (optionnel)'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèce'), ('cheque', 'Chèque'), ('virement', 'Virement')], default='espece', max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('abandonne', 'Abandonné')], default='actif', max_length=20),
        ),

        # Étape 1 : Supprimer l'ancien M2M sans through
        # La table auto n'existe pas en DB → database_operations vide
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='etudiant',
                    name='formations_suivies',
                ),
            ],
        ),

        # Étape 2 : Créer EtudiantFormation
        # La table existe déjà en DB (créée manuellement) → database_operations vide
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='EtudiantFormation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date_inscription_formation', models.DateField(auto_now_add=True)),
                        ('attestation', models.BooleanField(default=False)),
                        ('date_attestation', models.DateField(blank=True, null=True)),
                        ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_formations', to='etudiants.etudiant')),
                        ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_formations', to='formation.formation')),
                    ],
                    options={
                        'verbose_name': 'Inscription formation',
                        'verbose_name_plural': 'Inscriptions formations',
                        'ordering': ['date_inscription_formation'],
                        'unique_together': {('etudiant', 'formation')},
                    },
                ),
            ],
        ),

        # Étape 3 : Recréer le M2M avec through=EtudiantFormation
        # Pas de table à créer en DB pour un M2M avec through explicite → database_operations vide
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='etudiant',
                    name='formations_suivies',
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="Formations suivies par l'étudiant",
                        related_name='etudiants',
                        through='etudiants.EtudiantFormation',
                        to='formation.formation',
                    ),
                ),
            ],
        ),
    ]