# Generated by Django 5.2.7 on 2026-04-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0007_alter_document_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['-date_inscription', '-date_creation'], 'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
    ]
