# Generated by Django 5.2.7 on 2026-04-14 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0008_alter_etudiant_options'),
        ('formation', '0005_alter_formation_niveau'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantRelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relance', models.DateField()),
                ('commentaire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('aujourd_hui', "Aujourd'hui"), ('en_retard', 'En retard'), ('fait', 'Fait')], default='a_venir', max_length=20)),
                ('date_action', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_etudiants_creees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='etudiants.etudiant')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_etudiants', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Relance étudiant',
                'verbose_name_plural': 'Relances étudiants',
                'ordering': ['date_relance'],
            },
        ),
    ]
