# Generated by Django 5.2.7 on 2026-04-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0009_etudiantrelance'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantrelance',
            name='notes_action',
            field=models.TextField(blank=True, default=''),
        ),
    ]
